# Generated by Django 4.0.4 on 2023-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.TextField(default='wala shy'),
            preserve_default=False,
        ),
    ]
